remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme

title: Zoho Case Studies
tagline: Technical documentation and architectural case studies for Zoho-based business applications.
description: A comprehensive portfolio of business process automations and ERP solutions architected within the Zoho Ecosystem.
